//! Generated Rust bindings for Roost's gRPC IPC contract.
//!
//! The schema lives at `proto/roost.proto`; the bindings are regenerated by
//! `build.rs` on every build. Re-export the generated module under a
//! versioned namespace so callers write `roost_proto::v1::...`.

#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::large_enum_variant)]

pub mod v1 {
    tonic::include_proto!("roost.v1");
}

/// Server's expected `protocol_version` in `IdentifyResponse`. Bumped on
/// every breaking schema change. See `proto/CHANGELOG.md`.
pub const PROTOCOL_VERSION: u32 = 1;
