# shellcheck shell=bash
#
# Shared toolkit-agnostic bundling stages for mac/scripts/bundle.sh and
# mac/scripts/bundle-iced.sh.
#
# Sourced, not executed: callers set `set -euo pipefail` themselves and
# source this file after computing SCRIPT_DIR/MAC_DIR/REPO_ROOT. Every
# function here is parameterized — no assumptions about app name, bundle
# dir, or entitlements paths baked in as globals.

# roost_check_libghostty_archive REPO_ROOT
#
# Sanity check: the static libghostty-vt archive must exist or `swift
# build` / `cargo build` will fail at the linker. The same precondition
# the Mac README documents.
roost_check_libghostty_archive() {
  local repo_root="$1"
  if [ ! -f "${repo_root}/third_party/ghostty/out/lib/libghostty-vt.a" ]; then
    echo "error: libghostty-vt static archive not built." >&2
    echo "       Run: ${repo_root}/third_party/ghostty/build.sh" >&2
    exit 1
  fi
}

# roost_workspace_version REPO_ROOT
#
# Prints the marketing version derived from the workspace's single
# source of truth — `[workspace.package].version` in Cargo.toml — so a
# local bundle build reports the same version the GTK UI, the .deb, and
# `roostctl identify` do. Callers should let $ROOST_VERSION override the
# result. The `^version` anchor matches only the top-level key, not the
# `version = "…"` entries nested under `[workspace.dependencies]`.
roost_workspace_version() {
  local repo_root="$1"
  local cargo_version
  # Explicit failure check: command substitution suppresses errexit in
  # bash 3.2, so without it a missing/unreadable version line would
  # silently become 0.0.0 where the original inline pipeline aborted
  # under pipefail.
  cargo_version="$(grep -E '^version[[:space:]]*=' "${repo_root}/Cargo.toml" | head -1 \
    | sed -E 's/^version[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/')" || {
    echo "error: failed to read workspace version from ${repo_root}/Cargo.toml" >&2
    return 1
  }
  echo "${cargo_version:-0.0.0}"
}

# roost_assemble_skeleton APP_DIR
#
# Fresh bundle skeleton: Contents/MacOS + Contents/Resources. Both
# bundle scripts wipe and recreate on every run (no incremental
# state) so a stale bundle can't wear a previous build's leftovers.
roost_assemble_skeleton() {
  local app_dir="$1"
  echo "==> Assembling ${app_dir}"
  rm -rf "${app_dir}"
  mkdir -p "${app_dir}/Contents/MacOS"
  mkdir -p "${app_dir}/Contents/Resources"
}

# roost_stamp_plist TEMPLATE_PLIST APP_DIR VERSION
#
# Info.plist with version substitution. `sed -e s/.../.../g` is
# portable across BSD + GNU sed; quoting `@VERSION@` and using a
# unique-enough sentinel keeps the substitution unambiguous.
roost_stamp_plist() {
  local template_plist="$1"
  local app_dir="$2"
  local version="$3"
  echo "==> Stamping Info.plist (version=${version})"
  sed -e "s/@VERSION@/${version}/g" "${template_plist}" \
    > "${app_dir}/Contents/Info.plist"
}

# roost_write_pkginfo APP_DIR
#
# Classic four-byte PkgInfo so Finder recognizes the bundle type
# without leaning on Info.plist alone. macOS tolerates a missing
# PkgInfo nowadays but Spotlight prefers it.
roost_write_pkginfo() {
  local app_dir="$1"
  printf "APPL????" > "${app_dir}/Contents/PkgInfo"
}

# roost_install_app_icon ICON_COMPOSER_SRC ICON_SRC APP_DIR
#
# App icon. On macOS 26 (Tahoe) a loose .icns is treated as legacy and
# inset on the system glass tile (a gray frame around the art). The fix
# is a compiled Icon Composer catalog (generated by
# packaging/icon/generate_icons.py) — `actool` renders it into
# Assets.car + a flattened AppIcon.icns, and Tahoe then fills the tile
# edge-to-edge (parity with ghostty/cmux). `actool` ships with full
# Xcode, not the bare Command Line Tools, so we fall back to the
# committed flat .icns when it's unavailable — that still builds a
# launchable bundle, just with the framed legacy icon on Tahoe.
# CFBundleIconName=AppIcon (set in the Info.plist template) routes the
# OS to the catalog; the .icns covers pre-Tahoe and the no-actool path.
#
# Reads LSMinimumSystemVersion back from APP_DIR's already-stamped
# Info.plist, so the caller must stamp Info.plist before calling this.
roost_install_app_icon() {
  local icon_composer_src="$1"
  local icon_src="$2"
  local app_dir="$3"

  local icon_done=0
  if [ -d "${icon_composer_src}" ] && command -v xcrun >/dev/null 2>&1 \
     && xcrun --find actool >/dev/null 2>&1; then
    # Match the bundle's own minimum OS so the catalog targets what the app ships.
    local min_os
    min_os="$(/usr/libexec/PlistBuddy -c 'Print :LSMinimumSystemVersion' \
      "${app_dir}/Contents/Info.plist" 2>/dev/null || echo 26.0)"
    local actool_tmp
    actool_tmp="$(mktemp -d)"
    echo "==> Compiling AppIcon.icon with actool (Tahoe glass icon, min ${min_os})"
    if xcrun actool "${icon_composer_src}" \
         --compile "${actool_tmp}" \
         --platform macosx \
         --minimum-deployment-target "${min_os}" \
         --app-icon AppIcon \
         --output-partial-info-plist "${actool_tmp}/partial.plist" \
         --errors --warnings >/dev/null 2>&1 \
       && [ -f "${actool_tmp}/Assets.car" ]; then
      cp "${actool_tmp}/Assets.car" "${app_dir}/Contents/Resources/Assets.car"
      # actool also emits a flattened .icns — keep it as the pre-Tahoe fallback.
      [ -f "${actool_tmp}/AppIcon.icns" ] \
        && cp "${actool_tmp}/AppIcon.icns" "${app_dir}/Contents/Resources/AppIcon.icns"
      echo "    Compiled: ${app_dir}/Contents/Resources/Assets.car"
      icon_done=1
    else
      echo "    warn: actool failed; falling back to flat AppIcon.icns" >&2
    fi
    rm -rf "${actool_tmp}"
  fi
  if [ "${icon_done}" -eq 0 ]; then
    if [ -f "${icon_src}" ]; then
      echo "==> Including flat AppIcon.icns (no actool — Tahoe will show the framed legacy icon)"
      cp "${icon_src}" "${app_dir}/Contents/Resources/AppIcon.icns"
    else
      echo "==> No app icon found; bundle ships without a custom icon"
    fi
  fi
}

# roost_find_cargo
#
# Prints the cargo to invoke. Discovers `cargo` on PATH instead of
# hardcoding ~/.cargo/bin/cargo — release runners may have cargo at a
# different prefix (toolchain managed by mise / rustup / system
# package). Falling back to the literal path preserves the prior
# behavior for the common dev case.
roost_find_cargo() {
  local cargo_bin
  cargo_bin="$(command -v cargo || true)"
  if [ -z "${cargo_bin}" ] && [ -x "${HOME}/.cargo/bin/cargo" ]; then
    cargo_bin="${HOME}/.cargo/bin/cargo"
  fi
  if [ -z "${cargo_bin}" ]; then
    echo "error: cargo not found on PATH or at ~/.cargo/bin/cargo" >&2
    exit 1
  fi
  echo "${cargo_bin}"
}

# roost_setup_cargo_profile CONFIG
#
# Sets ROOST_CARGO_PROFILE_FLAG (word-split deliberately; empty for
# debug) and ROOST_CARGO_PROFILE_DIR in the caller's scope — the same
# caller-scope convention roost_setup_signing uses.
roost_setup_cargo_profile() {
  ROOST_CARGO_PROFILE_FLAG="--release"
  ROOST_CARGO_PROFILE_DIR="release"
  if [ "$1" = "debug" ]; then
    ROOST_CARGO_PROFILE_FLAG=""
    ROOST_CARGO_PROFILE_DIR="debug"
  fi
}

# roost_cargo_target_dir REPO_ROOT
#
# Prints the artifact root, honoring CARGO_TARGET_DIR — shared caches
# (e.g. sccache + CI matrices that fan out across configs) routinely
# override the default `<repo>/target/` location. Cargo resolves a
# relative CARGO_TARGET_DIR from its own CWD (the repo root, where the
# build subshells cd) — discovery anchors the same way so the two
# can't diverge.
roost_cargo_target_dir() {
  local repo_root="$1"
  local cargo_target="${CARGO_TARGET_DIR:-${repo_root}/target}"
  case "${cargo_target}" in
    /*) ;;
    *) cargo_target="${repo_root}/${cargo_target}" ;;
  esac
  echo "${cargo_target}"
}

# roost_build_and_embed_roostctl REPO_ROOT APP_DIR CONFIG
#
# Embed roostctl under Contents/Resources/bin/ so `claude install`
# invoked from inside the bundled app writes hook paths that point at
# the bundled binary, not a dev-machine target/ path. The CLI build is
# fast and tracked through the same Cargo cache as any cargo build
# invocation; rebuilding here keeps the bundle in lockstep with
# whatever roost-cli source the developer has checked out.
roost_build_and_embed_roostctl() {
  local repo_root="$1"
  local app_dir="$2"
  local config="$3"

  local cargo_bin
  cargo_bin="$(roost_find_cargo)"
  roost_setup_cargo_profile "${config}"
  local cargo_profile_flag="${ROOST_CARGO_PROFILE_FLAG}"
  local cargo_profile_dir="${ROOST_CARGO_PROFILE_DIR}"
  echo "==> Building roostctl (cargo build -p roost-cli --${cargo_profile_dir})"
  (
    # shellcheck disable=SC2164  # callers run this lib under `set -e`
    cd "${repo_root}"
    # shellcheck disable=SC2086
    "${cargo_bin}" build -p roost-cli ${cargo_profile_flag}
  )

  local cargo_target
  cargo_target="$(roost_cargo_target_dir "${repo_root}")"
  local roostctl_src="${cargo_target}/${cargo_profile_dir}/roostctl"
  if [ ! -x "${roostctl_src}" ]; then
    echo "error: cargo build did not produce ${roostctl_src}" >&2
    exit 1
  fi
  mkdir -p "${app_dir}/Contents/Resources/bin"
  cp "${roostctl_src}" "${app_dir}/Contents/Resources/bin/roostctl"
  chmod +x "${app_dir}/Contents/Resources/bin/roostctl"
  echo "    Embedded: ${app_dir}/Contents/Resources/bin/roostctl"
}

# roost_setup_signing ENT_FILE ROOSTCTL_ENT_FILE
#
# Signing setup. When ROOST_DEVELOPER_ID_IDENTITY is set (release CI, or
# a dev who holds the cert) we sign with that Developer ID + a secure
# `--timestamp` so the bundle can be notarized. Otherwise we fall back
# to ad-hoc (`-`) signing: fine for local launch, but Gatekeeper will
# warn and notarization is impossible.
#
# Failure handling: a botched signature is release-blocking (Gatekeeper
# reject, notarization fail, quarantined installs). Default is fail
# hard; the `ROOST_ALLOW_UNSIGNED=1` env var bypasses for the rare dev
# case where Xcode CLT codesign is missing.
#
# Sets SIGN_IDENTITY, TS_FLAG, and ROOST_SIGN_ENT_FILE in the caller's
# scope, and defines the codesign_or_die / codesign_framework_or_die
# functions (also in the caller's scope — this is bash, functions
# defined here are global to the sourcing script).
# ROOST_SIGN_ENT_FILE stays global (not a local) because
# codesign_or_die's default-entitlements argument reads it after this
# function has already returned. Returns 1 (without exiting) when
# signing must be skipped entirely because ROOST_ALLOW_UNSIGNED=1
# bypassed a missing entitlements file or missing codesign — callers
# should skip calling the sign functions in that case.
roost_setup_signing() {
  ROOST_SIGN_ENT_FILE="$1"
  local ent_file="$1"
  local roostctl_ent_file="$2"

  SIGN_IDENTITY="${ROOST_DEVELOPER_ID_IDENTITY:--}"
  # `--timestamp` only with a real identity; ad-hoc signing can't be
  # timestamped. Kept as a plain (unquoted-on-use) string so it expands
  # to nothing when empty — bash 3.2-safe (no empty-array expansion
  # under `set -u`).
  TS_FLAG=""
  if [ "${SIGN_IDENTITY}" != "-" ]; then
    TS_FLAG="--timestamp"
  fi

  if [ ! -f "${ent_file}" ] || [ ! -f "${roostctl_ent_file}" ]; then
    # The entitlements files are committed and carry the app's TCC
    # capabilities (mic/camera/Apple-events); a missing one must not
    # silently ship an unsigned bundle that drops them. Fail hard like
    # the missing-codesign case, unless the operator explicitly opts
    # into an unsigned build.
    if [ "${ROOST_ALLOW_UNSIGNED:-0}" = "1" ]; then
      echo "==> warn: missing entitlements file (${ent_file} or ${roostctl_ent_file}); ROOST_ALLOW_UNSIGNED=1 set, shipping unsigned"
      return 1
    else
      echo "error: missing entitlements file (${ent_file} or ${roostctl_ent_file}) (set ROOST_ALLOW_UNSIGNED=1 to bypass)" >&2
      exit 1
    fi
  elif ! command -v codesign >/dev/null 2>&1; then
    # codesign absent (no Xcode CLT). Honor the fail-hard intent above:
    # a missing signer would silently ship an unsigned bundle, so error
    # out unless the operator explicitly opts into an unsigned build.
    if [ "${ROOST_ALLOW_UNSIGNED:-0}" = "1" ]; then
      echo "==> warn: codesign not found; ROOST_ALLOW_UNSIGNED=1 set, shipping unsigned"
      return 1
    else
      echo "error: codesign not found (set ROOST_ALLOW_UNSIGNED=1 to bypass)" >&2
      exit 1
    fi
  fi

  if [ "${SIGN_IDENTITY}" = "-" ]; then
    echo "==> Ad-hoc codesign (set ROOST_DEVELOPER_ID_IDENTITY for a notarizable build)"
  else
    echo "==> Developer ID codesign (identity: ${SIGN_IDENTITY})"
  fi

  # shellcheck disable=SC2329  # invoked by the sourcing script after this function returns
  codesign_or_die() {
    local target="$1"
    # Optional per-target entitlements; defaults to the app's file. The
    # roostctl helper passes its own narrower file.
    local ent="${2:-${ROOST_SIGN_ENT_FILE}}"
    # shellcheck disable=SC2086  # TS_FLAG must word-split (empty => no flag)
    if codesign --force --sign "${SIGN_IDENTITY}" \
         --entitlements "${ent}" \
         --options runtime \
         ${TS_FLAG} \
         "${target}"
    then
      return 0
    fi
    if [ "${ROOST_ALLOW_UNSIGNED:-0}" = "1" ]; then
      echo "    warn: codesign(${target}) failed; ROOST_ALLOW_UNSIGNED=1 set, continuing"
      return 0
    fi
    echo "    error: codesign(${target}) failed (set ROOST_ALLOW_UNSIGNED=1 to bypass)" >&2
    exit 1
  }

  # Sparkle.framework is signed --deep but WITHOUT --entitlements: the
  # framework + its nested helpers (XPCServices/*.xpc, Updater.app,
  # Autoupdate) carry their own designated requirements, and forcing the
  # app's entitlements onto them can break Sparkle's XPC handshake. The
  # app's `disable-library-validation` entitlement (on the outer bundle)
  # is what lets it load this ad-hoc framework. --deep is safe here (a
  # framework signed with uniform options) — it is only dangerous on the
  # outer .app, where it would clobber these nested signatures.
  # shellcheck disable=SC2329  # invoked by the sourcing script after this function returns
  codesign_framework_or_die() {
    local target="$1"
    # shellcheck disable=SC2086  # TS_FLAG must word-split (empty => no flag)
    if codesign --force --sign "${SIGN_IDENTITY}" \
         --options runtime \
         --deep \
         ${TS_FLAG} \
         "${target}"
    then
      return 0
    fi
    if [ "${ROOST_ALLOW_UNSIGNED:-0}" = "1" ]; then
      echo "    warn: codesign(${target}) failed; ROOST_ALLOW_UNSIGNED=1 set, continuing"
      return 0
    fi
    echo "    error: codesign(${target}) failed (set ROOST_ALLOW_UNSIGNED=1 to bypass)" >&2
    exit 1
  }

  return 0
}
