#!/usr/bin/env bash
# Roost.app bundling — Phase 6a M7.
#
# Wraps the SwiftPM executable output into a proper macOS .app bundle
# so the binary can be Finder-launched / Dock-pinned / referenced by
# its bundle identifier instead of being run from the SwiftPM build
# tree like a CLI.
#
# What this script does:
#   1. Builds the Roost executable in the requested configuration
#      (default: release).
#   2. Assembles `mac/build/Roost.app` with the standard macOS bundle
#      layout — Contents/MacOS/Roost, Contents/Info.plist,
#      Contents/Resources/.
#   3. Substitutes @VERSION@ in `mac/Resources/Info.plist.template`
#      with the value of $ROOST_VERSION (or the project default).
#   4. Copies the SwiftPM-generated `Roost_Roost.bundle` (the
#      themes resource bundle that `Bundle.module` reads from) and
#      any other bundles the swift build path produced into
#      Contents/Resources/.
#   5. Installs the app icon. Prefers the Tahoe glass icon: compiles
#      `mac/AppIcon.icon` (Icon Composer source, generated by
#      packaging/icon/generate_icons.py) with `actool` into Assets.car.
#      Falls back to the flat `mac/Resources/AppIcon.icns` when `actool`
#      is unavailable (no full Xcode). See packaging/icon/README.md.
#
# What this script also does (issue #122):
#   * Embeds Sparkle.framework under Contents/Frameworks and signs it
#     inside-out (before the outer .app) so the app can auto-update.
#
# What this script does NOT do (Phase 8 follow-ups, intentional):
#   * Code-sign with a Developer ID certificate (ad-hoc until #83).
#   * Notarize via `notarytool`.
#   * Build a DMG (release.yml's `make-dmg` step does that).
#   * EdDSA-sign the DMG / publish the appcast (release.yml, issue #122).
#
# The toolkit-agnostic stages (version derivation, icon pipeline,
# roostctl embed, signing machinery, the libghostty-vt precondition)
# live in bundle-lib.sh, shared with bundle-iced.sh.
#
# Usage:
#   ./mac/scripts/bundle.sh                 # release build
#   ./mac/scripts/bundle.sh debug           # debug build
#   ROOST_VERSION=0.2.0 ./mac/scripts/bundle.sh
#
#   open mac/build/Roost.app                # launch the bundle

set -euo pipefail

CONFIG="${1:-release}"
case "${CONFIG}" in
  release|debug) ;;
  *)
    echo "error: configuration must be 'release' or 'debug', got '${CONFIG}'" >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAC_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${MAC_DIR}/.." && pwd)"

# shellcheck source=mac/scripts/bundle-lib.sh
source "${SCRIPT_DIR}/bundle-lib.sh"

# Default the marketing version to the workspace's single source of
# truth — see roost_workspace_version in bundle-lib.sh — so a local
# `bundle.sh debug` reports the same version the GTK UI, the .deb, and
# `roostctl identify` do. The release workflow still overrides
# ROOST_VERSION from the git tag (asserted to match Cargo.toml).
VERSION="${ROOST_VERSION:-$(roost_workspace_version "${REPO_ROOT}")}"
APP_NAME="Roost"
BUNDLE_ID="ai.stridelabs.Roost"
TEMPLATE_PLIST="${MAC_DIR}/Resources/Info.plist.template"
ICON_SRC="${MAC_DIR}/Resources/AppIcon.icns"
ICON_COMPOSER_SRC="${MAC_DIR}/AppIcon.icon"

OUT_DIR="${MAC_DIR}/build"
APP_DIR="${OUT_DIR}/${APP_NAME}.app"

roost_check_libghostty_archive "${REPO_ROOT}"

echo "==> Building Roost (${CONFIG}) from SwiftPM"
pushd "${MAC_DIR}" >/dev/null
swift build -c "${CONFIG}" --product Roost
popd >/dev/null

# Discover the SwiftPM bin path dynamically (same call reused for the resource
# bundles below) rather than hardcoding `arm64-apple-macosx`, so the script
# works regardless of the toolchain's target triple.
SWIFT_BIN_DIR="$(cd "${MAC_DIR}" && swift build -c "${CONFIG}" --show-bin-path)"
SWIFT_BUILD_BIN="${SWIFT_BIN_DIR}/Roost"
if [ ! -x "${SWIFT_BUILD_BIN}" ]; then
  echo "error: swift build did not produce ${SWIFT_BUILD_BIN}" >&2
  exit 1
fi

roost_assemble_skeleton "${APP_DIR}"

cp "${SWIFT_BUILD_BIN}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"
chmod +x "${APP_DIR}/Contents/MacOS/${APP_NAME}"

roost_stamp_plist "${TEMPLATE_PLIST}" "${APP_DIR}" "${VERSION}"
roost_write_pkginfo "${APP_DIR}"

# Resource bundles SwiftPM emits — the .app ships them so the running
# app can read its resources. `Roost_Roost.bundle` carries our theme
# files (Resources/themes/), loaded via `Bundle.roostResources`.
#
# Discover the SwiftPM bin path dynamically. The prior hardcoded
# `arm64-apple-macosx` path failed on Intel macOS runners
# (Phase 8 release-CI matrix includes x86_64). `swift build
# --show-bin-path` prints the exact directory containing the
# built artifacts for the current toolchain + target triple +
# config.
echo "==> Copying SwiftPM resource bundles"
# These live under Contents/Resources (NOT the .app root: nested bundles
# outside Contents/ break codesigning). `Bundle.module`'s generated
# accessor would instead look at `Bundle.main.bundleURL/<name>.bundle`
# (the .app root) plus a compile-time build path — neither exists on a
# clean install, so it `fatalError`ed there. The Swift side resolves the
# themes bundle from Contents/Resources via `Bundle.main` instead (see
# `Bundle.roostResources` in Theme.swift), never `Bundle.module`.
for bundle in "${SWIFT_BIN_DIR}"/*.bundle; do
  [ -d "${bundle}" ] || continue
  cp -R "${bundle}" "${APP_DIR}/Contents/Resources/"
done

# Sparkle.framework — auto-update (issue #122). SwiftPM copies the
# framework next to the built binary; we embed it under
# Contents/Frameworks/ where the Roost binary's
# `@executable_path/../Frameworks` rpath (Package.swift) resolves
# `@rpath/Sparkle.framework/Versions/B/Sparkle`. Without this the app
# aborts at launch with `dyld: Library not loaded`. `cp -R` preserves
# the Versions/Current symlink farm that codesign requires.
echo "==> Embedding Sparkle.framework"
SPARKLE_FW_SRC="${SWIFT_BIN_DIR}/Sparkle.framework"
if [ ! -d "${SPARKLE_FW_SRC}" ]; then
  echo "error: Sparkle.framework not found at ${SPARKLE_FW_SRC}" >&2
  echo "       (did 'swift build' fetch the Sparkle SPM artifact?)" >&2
  exit 1
fi
mkdir -p "${APP_DIR}/Contents/Frameworks"
cp -R "${SPARKLE_FW_SRC}" "${APP_DIR}/Contents/Frameworks/"
echo "    Embedded: ${APP_DIR}/Contents/Frameworks/Sparkle.framework"

roost_install_app_icon "${ICON_COMPOSER_SRC}" "${ICON_SRC}" "${APP_DIR}"

# M8: embed roostctl under Contents/Resources/bin/ so `claude
# install` invoked from inside Roost.app writes hook paths that
# point at the bundled binary, not a dev-machine target/ path.
roost_build_and_embed_roostctl "${REPO_ROOT}" "${APP_DIR}" "${CONFIG}"

# Signing. When ROOST_DEVELOPER_ID_IDENTITY is set (release CI, or a dev who
# holds the cert) we sign with that Developer ID + a secure `--timestamp` so the
# bundle can be notarized. Otherwise we fall back to ad-hoc (`-`) signing: fine
# for local launch, but Gatekeeper will warn and notarization is impossible.
# The inner→outer order (embedded roostctl first, then the .app) is required —
# codesign seals nested code into the outer signature.
ENT_FILE="${MAC_DIR}/Resources/Roost.entitlements"
# The bundled roostctl helper gets a narrower entitlements file: it never
# records audio/video or sends Apple events, so it must not inherit the app's
# capture entitlements (least privilege; cf. cmux's cmux-helper.entitlements).
ROOSTCTL_ENT_FILE="${MAC_DIR}/Resources/roostctl.entitlements"
if roost_setup_signing "${ENT_FILE}" "${ROOSTCTL_ENT_FILE}"; then
  codesign_or_die "${APP_DIR}/Contents/Resources/bin/roostctl" "${ROOSTCTL_ENT_FILE}"
  codesign_framework_or_die "${APP_DIR}/Contents/Frameworks/Sparkle.framework"
  codesign_or_die "${APP_DIR}"
fi

echo "==> Bundled: ${APP_DIR}"
echo "    Bundle ID:    ${BUNDLE_ID}"
echo "    Version:      ${VERSION}"
echo "    Executable:   ${APP_DIR}/Contents/MacOS/${APP_NAME}"
echo "    Embedded CLI: ${APP_DIR}/Contents/Resources/bin/roostctl"
echo
echo "Launch with: open '${APP_DIR}'"
